apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: User Login App
  # This is an extra long description
  description: This microservice connects with our authentication framework so users can login to their profile to view transaction history, upgrades, and manage invites.
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: Production
  owner: marketing-team
  providesApis:
    - petstore
    - streetlights
    - hello-world
